apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- demo.yaml

patches:
- target:
    kind: Application
  patch: |-
    kind: Application
    metadata:
      name: .*
    spec:
      source:
        repoURL: https://github.com/alpcrimea/argo-combined-demo