apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-workflows/blob/v3.4.5/manifests/quick-start-minimal.yaml
- workflow-role-binding.yaml
- workflow-role.yaml

patchesStrategicMerge:
- argo-server-service.yaml
- workflow-controller-cm.yaml
- argo-binding.yaml
- argo-server-binding.yaml
